### ISSUE TITLE
crudy logo

### ISSUE THREAD

**Issue by moklick** [g-div/crudy#1]
![crudy](https://cloud.githubusercontent.com/assets/2857535/9075168/e1130cb2-3b11-11e5-8548-aab2cc8985ee.png)

Not really a logo yet, but at least a part of it :)

**Comment by moklick** [comment]
![crudy-small](https://cloud.githubusercontent.com/assets/2857535/9075332/fa99d7a4-3b13-11e5-99cb-189b1c67f08c.png)

we better use this for the readme

**Comment by g-div** [comment]
Yeah !

Nice, thank you. :v:
