### ISSUE TITLE
Heads-up: dogwater 1.0.0 here, bedwetter 2.0.0 on the horizon

### ISSUE THREAD

**Issue by devinivy** [g-div/crudy#4]
Just letting you know that dogwater has recently hit 1.0.0 with some breaking changes.  Correspondingly, bedwetter 2.0.0 will come out soon with some breaking changes.  I realize they're only peer dependencies of this project, but I figured I'd give you a heads-up if it'll affect your package.json, examples, or tests :)

**Comment by g-div** [comment]
Great news, actually ! 
I was aware that `dogwater v.1.0.0` was already available in npm. I've also already noticed that `dogwater@1.0.0` is not compatible with `bedwetter@1.8.x`. 

I will be hapi...happy to update the package once the new bedwetter's version will be available at npm.

Thank you for keeping us updated!
